apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: openstack-neutron-operator-kog
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/openstack-neutron-operator-kog
    version: "0.1.0"
